# Generated by Django 2.0.7 on 2018-07-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('gender', models.SmallIntegerField(choices=[(1, 'мальчик'), (0, 'девочка')], verbose_name='Пол')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.CharField(max_length=100, verbose_name='Фото')),
                ('grade', models.SmallIntegerField(null=True, verbose_name='Класс')),
                ('is_study', models.BooleanField(verbose_name='Учится?')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_time', models.DateTimeField(null=True, verbose_name='Время прибытия')),
                ('income_escort', models.SmallIntegerField(choices=[(0, 'отец'), (1, 'мать')], null=True, verbose_name='Сопровождающее лицо')),
                ('outcome_time', models.DateTimeField(null=True, verbose_name='Время прибытия')),
                ('outcome_escort', models.SmallIntegerField(choices=[(0, 'отец'), (1, 'мать')], null=True, verbose_name='Сопровождающее лицо')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manger.Baby', verbose_name='Ребенок')),
            ],
        ),
    ]
